# -*- coding: utf-8 -*-
"""PracticingWithAWS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AACIcjdy7R4ItfhZ6z4TKrDeKQ9hTDx8
"""

import json
import boto3 #교육때 배웠던 거
import random #csv 채널에서 사용


bedrock = boto3.client('bedrock-runtime', region_name='us-east-1') #교육 때 배운 내용
s3 = boto3.client('s3')

S3_BUCKET = 'smct-42'
S3_KEY = 'jlpt_n2_kanji_words_only.csv' #파일 불러오기

def load_csv_from_s3(bucket, key):
    response = s3.get_object(Bucket=bucket, Key=key)
    content = response['Body'].read().decode('utf-8')
    return [line.strip() for line in content.splitlines() if line.strip()]

def lambda_handler(event, context):
    headers = {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Allow-Methods': 'GET,POST,OPTIONS'
    }

    try:
        kanji_words = load_csv_from_s3(S3_BUCKET, S3_KEY) #내 버킷으로 접근해서 데이터 가져오기

        if len(kanji_words) < 5: #지피티에게 물어 본 예외처리
            kanji_words = ["一人一人", "一仕事", "一層", "一応", "一斉"]

        recommended_items = random.sample(kanji_words, 5) #csv 파일에서 무작위로 5개 뽑음


        prompt = f"다음 한자로 문장 만들어 봐: {', '.join(recommended_items)}. 40자 이내로"
#저 명령을 베드록이 받고, 베드록이 직접 내 파일을 분석한 다음 데이터 분석 결과를 내놓음(36줄에서 베드록 호출)
        response = bedrock.invoke_model(
            modelId='anthropic.claude-3-sonnet-20240229-v1:0',
            contentType='application/json',
            accept='application/json',

        response = bedrock.invoke_model(
            modelId='anthropic.claude-3-sonnet-20240229-v1:0',
            contentType='application/json',
            accept='application/json',
            body=json.dumps({
                "anthropic_version": "bedrock-2023-05-31",
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 200,
                "temperature": 0.5, #교육 때 배웠던 내용
            })
        )

        response_body = json.loads(response.get('body').read())
        ai_reasoning = response_body['content'][0]['text'] #파싱

        return {
            'statusCode': 200,
            'headers': headers,
            'body': json.dumps({
                'recommendations': recommended_items,
                'ai_reasoning': ai_reasoning
            })
        }

    except Exception as e: #이건 지피티한테 물어 본 연결 안 됐을 때 코드
        return {
            'statusCode': 500,
            'headers': headers,
            'body': json.dumps({
                'error': str(e),
                'message': 'Lambda 처리 중 오류 발생 — S3 경로, IAM 권한, 또는 Bedrock 설정 확인 필요.'
            })
        }